# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-27 17:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('restendpoint', '0003_userinfo_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statusId', models.CharField(max_length=255)),
                ('visibility', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('text', models.CharField(max_length=255)),
                ('time', models.TimeField(auto_now=True)),
                ('category', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='userinfo',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='dob',
            field=models.DateField(blank=True, default=django.utils.datetime_safe.datetime.now),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='imgurl',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='password',
            field=models.CharField(blank=True, default=django.utils.datetime_safe.datetime.now, max_length=255),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='phone',
            field=models.CharField(blank=True, default=django.utils.datetime_safe.datetime.now, max_length=255),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='salt',
            field=models.CharField(blank=True, default=django.utils.datetime_safe.datetime.now, max_length=255),
        ),
        migrations.AddField(
            model_name='status',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restendpoint.UserInfo'),
        ),
    ]
